version: '3'
services:
  web:
    build: ./mysite
    command: python3 ./manage.py runserver 0.0.0.0:8000
    depends_on:
    - db
    - redis
    environment:
     - DATABASE_URL=postgres://postgres@db/postgres
     - REDIS_HOST=redis

  db:
    image: postgres:12.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
